language: python
python:
- '2.7'
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_30e3b2f76a9d_key -iv $encrypted_30e3b2f76a9d_iv
  -in id_ed25519.enc -out ~/.ssh/id_ed25519 -d
- chmod 400 ~/.ssh/id_ed25519
install:
- pip install ansible
jobs:
  include:
  - stage: deploy-staging
    script: ansible-playbook -i inventory.yml playbook.yml
      --user $ANSIBLE_USER --private-key ~/.ssh/id_ed25519
